skeptipay models and specs
KwaneleNdenze/SkeptiPay pull request #8
Opened 2022-06-22 10:11 UTC by KwaneleNdenze

2022-06-22 11:02 UTC, thatosmk commented on db/migrate/20220622092155_create_payments.rb
> +      t.string :status
make this an enum (which will be an `integer`). Have a look and see how they do enums in ruby

2022-06-22 11:02 UTC, thatosmk commented on db/migrate/20220622093223_create_withdrawals.rb
> +      t.string :status
make this an enum as well

2022-06-22 11:03 UTC, thatosmk commented on db/migrate/20220622093329_create_notifications.rb
> +      t.text :text
call it `content` or `body` or something more specific

2022-06-22 11:04 UTC, thatosmk commented
looks great, but also, have a look at having an `account` model that will have a `user_id` and a user will have an account and that account will have invoices, withdrawals etc

2022-06-22 11:06 UTC, thatosmk requested changes
add enums and perhaps think about having an accounts table.

2022-06-22 13:00 UTC, KwaneleNdenze commented on db/migrate/20220622093223_create_withdrawals.rb
> +      t.string :status
Made this change

2022-06-22 13:01 UTC, KwaneleNdenze commented on db/migrate/20220622093329_create_notifications.rb
> +      t.text :text
Made this change.

2022-06-22 14:05 UTC, KwaneleNdenze commented
> 

Made the change, please check if my implementation of the associations between user and account is correct

2022-06-22 14:43 UTC, thatosmk commented on app/models/notification.rb
> +  enum status: [:unread, :read]
also fix indentation in this file, it is not uniform

2022-06-22 14:43 UTC, thatosmk commented on app/models/payment.rb
> +  enum status: [:requested, :approved]
same comment as above regarding enums

2022-06-22 14:44 UTC, thatosmk commented on app/models/payment.rb
> +    end
you can add `default: 0` to the migration when you add the status column.

2022-06-22 14:44 UTC, thatosmk commented on app/models/payment.rb
> +  enum status: [:requested, :approved]
so no need to do this

2022-06-22 14:44 UTC, thatosmk commented on app/models/user.rb
> +   has_one :account
correct, so fix the association in the `account` model

2022-06-24 10:08 UTC, thatosmk commented on app/models/payment.rb
> +  enum status: {requested: 0, approved: 0}
cannot have the same integer value

2022-06-24 10:08 UTC, thatosmk commented on db/migrate/20220622092155_create_payments.rb
> +      t.string :status
make this an integer with default 0, then remove all your set default status methods

2022-06-24 10:17 UTC, thatosmk commented on app/models/notification.rb
> +  end
```suggestion
```

2022-06-24 10:19 UTC, thatosmk commented on app/models/payment.rb
> +  end
```suggestion
```

2022-06-24 12:54 UTC, thatosmk approved these changes
Great work dude

2022-06-24 12:57 UTC, merged